workflows:
  build-app:
    name: Build App
    max_build_duration: 60
    environment:
      node: 20.11.1
      java: 21
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Rebuild esbuild
        script: |
          npm rebuild esbuild

      - name: Fix vite permissions
        script: |
          chmod +x ./node_modules/.bin/vite || true

      - name: Build web assets
        script: |
          npx vite build

      - name: Capacitor sync
        script: |
          chmod +x ./node_modules/.bin/cap || true
          npx cap sync

      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Build iOS App
        script: |
          npx cap copy ios
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM=64UP78W834 | tee build.log

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      - ios/App/build/Release-iphoneos/App.app
