workflows:
  build-app:
    name: Build App
    max_build_duration: 60
    environment:
      node: 20.11.1
      java: 11
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Rebuild esbuild to ensure correct binary
        script: |
          npm rebuild esbuild

      - name: Fix vite permissions
        script: |
          chmod +x ./node_modules/.bin/vite || true

      - name: Build web assets
        script: |
          npx vite build

      - name: Fix capacitor permissions and sync
        script: |
          chmod +x ./node_modules/.bin/cap || true
          npx cap sync

      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Build iOS App
        script: |
          npx cap copy ios
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos clean build CODE_SIGN_STYLE=Automatic

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      - ios/App/build/Release-iphoneos/App.app
