workflows:
  build-app:
    name: Build Mashaweer App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_MANAGER: npm
        NODE_VERSION: 18.16.0
      node: $NODE_VERSION
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Rebuild esbuild (for Apple Silicon compatibility)
        script: |
          npm rebuild esbuild

      - name: Build web assets
        script: |
          npx vite build

      - name: Sync Capacitor plugins and copy web assets
        script: |
          npx cap sync

      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - dist/**
