workflows:
  build:
    name: Build iOS and Android
    max_build_duration: 60
    environment:
      node: 18.16.0
      java: 11
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web assets
        script: npm run build

      - name: Check dist directory content
        script: ls -la dist

      - name: Sync Capacitor plugins and copy web assets
        script: npx cap sync

      - name: Build Android
        script: |
          npx cap copy android
          cd android && ./gradlew assembleRelease

      - name: Build iOS
        script: |
          npx cap copy ios
          cd ios/App && xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos clean build CODE_SIGN_STYLE=Automatic

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      - ios/App/build/Release-iphoneos/App.app
