workflows:
  Build App:
    name: Build Mashaweer for Android and iOS

    environment:
      vars:
        BUNDLE_ID: "online.mashaweer"
        APP_NAME: "Mashaweer App"
      groups:
        - Appstore
      node: 20.14.0
      xcode: 15.2
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          chmod +x node_modules/.bin/cap
          node_modules/.bin/cap sync

      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Build iOS
        script: |
          cd ios
          xcodebuild \
            -workspace App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build

    artifacts:
      - android/app/build/outputs/**/*.aab
      - ios/build/Build/Products/Release-iphoneos/*.app
